# ДОМАШНЕЕ ЗАДАНИЕ 1. Дескриптивный анализ данных

Выполнил Фадеев Роман Андреевич гр. ИУ6-21М

## Цель работы

Приобрести опыт решения практических задач по анализу данных, таких как загрузка, трансформация, вычисление простых статистик и визуализация данных в виде графиков и диаграмм, посредством языка программирования Python.

## Вариант

In [113]:
surname = "Фаддев"  # Ваша фамилия

alp = 'абвгдеёжзийклмнопрстуфхцчшщъыьэюя'
w = [1, 42, 21, 21, 34,  6, 44, 26, 18, 44, 38, 26, 14, 43,  4, 49, 45,
        7, 42, 29,  4,  9, 36, 34, 31, 29,  5, 30,  4, 19, 28, 25, 33]

d = dict(zip(alp, w))
variant =  sum([d[el] for el in surname.lower()]) % 40 + 1

print("Задача № 1, шаг 5 - вариант: ", variant % 5 + 1)
print("задача № 2 - вариант: ", variant % 4 + 1)

Задача № 1, шаг 5 - вариант:  2
задача № 2 - вариант:  3

## Задача 1. Анализ индикаторов качества государственного управления (The Worldwide Government Indicators, WGI) (6 баллов)

В качестве индикатора далее необходимо использовать контроль над коррупцией (Control of Corruption) и его показатели `score` и `estimate`

- Набор данных:
    - [WGI](https://www.worldbank.org/content/dam/sites/govindicators/doc/wgidataset_with_sourcedata-2025.xlsx)
    - [Регионы](../data/A1_Descriptive_Analysis/regions.xlsx)
- [Описание WGI](https://www.worldbank.org/en/publication/worldwide-governance-indicators/documentation)

⚠️ **Замечание.** Исходный файл с данными редактировать нельзя.

1. Загрузите данные в DataFrame

In [114]:
%pip install openpyxl
import io
import requests
import pandas as pd

url = "https://www.worldbank.org/content/dam/sites/govindicators/doc/wgidataset_with_sourcedata-2025.xlsx"

headers = {
    "User-Agent": "Mozilla/5.0",
    "Accept": "*/*",
    "Referer": "https://www.worldbank.org/"
}

response = requests.get(url, headers=headers, timeout=60)
response.raise_for_status()

excel_file = io.BytesIO(response.content)

dfs = pd.read_excel(excel_file, engine="openpyxl", sheet_name=None)
df = pd.concat(dfs.values(), ignore_index=True)

df.head()

Requirement already satisfied: openpyxl in /usr/local/lib/python3.11/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.11/site-packages (from openpyxl) (2.0.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
Note: you may need to restart the kernel to use updated packages.

,ID variable (economy code/ gov. dimension/ year),Economy (name),Economy (code),Region,Income classification,Year,Governance dimension,Number of sources,Governance estimate (approx. -2.5 to +2.5),Standard error (estimate),...,OBI mean,PIA mean,PRS mean,RSF mean,VAB mean,VDM mean,WBS mean,WCY mean,WJP mean,WMO mean
0,ADOva1996,Andorra,ADO,NaN,NaN,1996,va,3,1.541954,0.301021,...,..,..,..,..,..,..,..,..,..,1
1,AFGva1996,Afghanistan,AFG,South Asia,Low income,1996,va,4,-2.235444,0.245080,...,..,..,..,..,..,0.246567,..,..,..,0.0625
2,AGOva1996,Angola,AGO,Sub-Saharan Africa,Lower middle income,1996,va,6,-1.746207,0.193985,...,..,..,0.25,..,..,0.320267,..,..,..,0.125
3,ALBva1996,Albania,ALB,Europe & Central Asia,Upper middle income,1996,va,5,-0.826077,0.221397,...,..,..,0.5,..,..,0.448356,..,..,..,0.25
4,AREva1996,United Arab Emirates,ARE,Middle East & North Africa,High income,1996,va,6,-0.848031,0.193985,...,..,..,0.583333,..,..,0.332567,..,..,..,0.6875

In [115]:
df.info()
df.columns

<class 'pandas.DataFrame'>
RangeIndex: 32403 entries, 0 to 32402
Data columns (total 51 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   ID variable (economy code/ gov. dimension/ year)  32403 non-null  str
 1   Economy (name)                                    32403 non-null  str
 2   Economy (code)                                    32403 non-null  str
 3   Region                                            31374 non-null  str
 4   Income classification                             31062 non-null  str
 5   Year                                              32403 non-null  int64
 6   Governance dimension                              32403 non-null  str
 7   Number of sources                                 32403 non-null  int64
 8   Governance estimate (approx. -2.5 to +2.5)        32403 non-null  float64
 9   Standard error (estimate)                         32403 non-null  float64
 10  Lower threshold (90% conf. int. estimate)         32403 non-null  float64
 11  Upper threshold (90% conf. int. estimate)         32403 non-null  float64
 12  Governance score (0-100)                          32403 non-null  float64
 13  Standard error (gov. score)                       32403 non-null  float64
 14  Lower threshold (90% conf. int. score)            32403 non-null  float64
 15  Upper threshold (90% conf. int. score)            32403 non-null  float64
 16  ADB mean                                          32403 non-null  object
 17  AFR mean                                          32403 non-null  object
 18  ARB mean                                          32403 non-null  object
 19  ASB mean                                          32403 non-null  object
 20  ASD mean                                          32403 non-null  object
 21  BPS mean                                          32403 non-null  object
 22  BTI mean                                          32403 non-null  object
 23  CCR mean                                          32403 non-null  object
 24  EBR mean                                          32403 non-null  object
 25  EIU mean                                          32403 non-null  object
 26  EQI mean                                          32403 non-null  object
 27  EUB mean                                          32403 non-null  object
 28  FRH mean                                          32403 non-null  object
 29  GCB mean                                          32403 non-null  object
 30  GCS mean                                          32403 non-null  object
 31  GII mean                                          32403 non-null  object
 32  GWP mean                                          32403 non-null  object
 33  HER mean                                          32403 non-null  object
 34  HRM mean                                          32403 non-null  object
 35  HUM mean                                          32403 non-null  object
 36  IFD mean                                          32403 non-null  object
 37  IJT mean                                          32403 non-null  object
 38  IRP mean                                          32403 non-null  object
 39  LBO mean                                          32403 non-null  object
 40  MSI mean                                          32403 non-null  object
 41  OBI mean                                          32403 non-null  object
 42  PIA mean                                          32403 non-null  object
 43  PRS mean                                          32403 non-null  object
 44  RSF mean                                          32403 non-null  object
 45  VAB mean                                          32403 non-null  object
 46  VDM mean                                          32403 non-null  object
 47  WBS mean                                          32403 non-null  object
 48  WCY mean                                          32403 non-null  object
 49  WJP mean                                          32403 non-null  object
 50  WMO mean                                          32403 non-null  object
dtypes: float64(8), int64(2), object(35), str(6)
memory usage: 14.4+ MB

Index(['ID variable (economy code/ gov. dimension/ year)', 'Economy (name)',
       'Economy (code)', 'Region', 'Income classification', 'Year',
       'Governance dimension', 'Number of sources',
       'Governance estimate (approx. -2.5 to +2.5)',
       'Standard error (estimate)',
       'Lower threshold (90% conf. int. estimate)',
       'Upper threshold (90% conf. int. estimate)', 'Governance score (0-100)',
       'Standard error (gov. score)', 'Lower threshold (90% conf. int. score)',
       'Upper threshold (90% conf. int. score)', 'ADB mean', 'AFR mean',
       'ARB mean', 'ASB mean', 'ASD mean', 'BPS mean', 'BTI mean', 'CCR mean',
       'EBR mean', 'EIU mean', 'EQI mean', 'EUB mean', 'FRH mean', 'GCB mean',
       'GCS mean', 'GII mean', 'GWP mean', 'HER mean', 'HRM mean', 'HUM mean',
       'IFD mean', 'IJT mean', 'IRP mean', 'LBO mean', 'MSI mean', 'OBI mean',
       'PIA mean', 'PRS mean', 'RSF mean', 'VAB mean', 'VDM mean', 'WBS mean',
       'WCY mean', 'WJP mean', 'WMO mean'],
      dtype='str')

In [116]:
df.columns

Index(['ID variable (economy code/ gov. dimension/ year)', 'Economy (name)',
       'Economy (code)', 'Region', 'Income classification', 'Year',
       'Governance dimension', 'Number of sources',
       'Governance estimate (approx. -2.5 to +2.5)',
       'Standard error (estimate)',
       'Lower threshold (90% conf. int. estimate)',
       'Upper threshold (90% conf. int. estimate)', 'Governance score (0-100)',
       'Standard error (gov. score)', 'Lower threshold (90% conf. int. score)',
       'Upper threshold (90% conf. int. score)', 'ADB mean', 'AFR mean',
       'ARB mean', 'ASB mean', 'ASD mean', 'BPS mean', 'BTI mean', 'CCR mean',
       'EBR mean', 'EIU mean', 'EQI mean', 'EUB mean', 'FRH mean', 'GCB mean',
       'GCS mean', 'GII mean', 'GWP mean', 'HER mean', 'HRM mean', 'HUM mean',
       'IFD mean', 'IJT mean', 'IRP mean', 'LBO mean', 'MSI mean', 'OBI mean',
       'PIA mean', 'PRS mean', 'RSF mean', 'VAB mean', 'VDM mean', 'WBS mean',
       'WCY mean', 'WJP mean', 'WMO mean'],
      dtype='str')

In [117]:
columns_needed = [
    "Economy (name)",
    "Economy (code)",
    "Region",
    "Year",
    "Governance dimension",
    "Governance score (0-100)",
    "Governance estimate (approx. -2.5 to +2.5)",
    "Standard error (gov. score)"
]

In [118]:
df_selected = df[columns_needed]

display(df_selected.head(20))

,Economy (name),Economy (code),Region,Year,Governance dimension,Governance score (0-100),Governance estimate (approx. -2.5 to +2.5),Standard error (gov. score)
0,Andorra,ADO,NaN,1996,va,83.837279,1.541954,5.268613
1,Afghanistan,AFG,South Asia,1996,va,17.723405,-2.235444,4.289510
2,Angola,AGO,Sub-Saharan Africa,1996,va,26.286262,-1.746207,3.395228
3,Albania,ALB,Europe & Central Asia,1996,va,42.390843,-0.826077,3.874993
4,United Arab Emirates,ARE,Middle East & North Africa,1996,va,42.006593,-0.848031,3.395228
5,Argentina,ARG,Latin America & Caribbean,1996,va,64.426408,0.432919,3.378128
6,Armenia,ARM,Europe & Central Asia,1996,va,42.310930,-0.830642,4.289510
7,Antigua and Barbuda,ATG,Latin America & Caribbean,1996,va,60.143210,0.188200,5.268613
8,Australia,AUS,East Asia & Pacific,1996,va,81.698045,1.419730,3.380890
9,Austria,AUT,Europe & Central Asia,1996,va,81.965561,1.435014,3.380890
10,Azerbaijan,AZE,Europe & Central Asia,1996,va,33.280657,-1.346585,3.663736
11,Burundi,BDI,Sub-Saharan Africa,1996,va,36.057534,-1.187928,4.289510
12,Belgium,BEL,Europe & Central Asia,1996,va,82.384636,1.458958,3.380890
13,Benin,BEN,Sub-Saharan Africa,1996,va,59.513789,0.152238,4.289510
14,Burkina Faso,BFA,Sub-Saharan Africa,1996,va,45.438931,-0.651925,3.874993
15,Bangladesh,BGD,South Asia,1996,va,51.285371,-0.317890,3.395228
16,Bulgaria,BGR,Europe & Central Asia,1996,va,61.319230,0.255392,3.395228
17,Bahrain,BHR,Middle East & North Africa,1996,va,37.750429,-1.091205,3.395228
18,"Bahamas, The",BHS,Latin America & Caribbean,1996,va,76.082483,1.098886,4.551353
19,Bosnia and Herzegovina,BIH,Europe & Central Asia,1996,va,53.455626,-0.193893,3.796046

In [119]:
import pandas as pd
from IPython.display import display
import ipywidgets as widgets

target_year = 2024

# Предположим, что df уже загружен

# Получаем все уникальные Governance dimension
dimensions = df_selected["Governance dimension"].unique()

# Создаём Dropdown для выбора измерения
dimension_dropdown = widgets.Dropdown(
    options=dimensions,
    description='Dimension:',
    value=dimensions[0],
    style={'description_width': 'initial'},
    layout=widgets.Layout(width='400px')
)

# Виджет для выбора года
year_dropdown = widgets.Dropdown(
    options=sorted(df_selected["Year"].unique(), reverse=True),
    description='Year:',
    value=target_year,
    style={'description_width': 'initial'},
    layout=widgets.Layout(width='200px')
)

# Функция обновления таблицы при выборе
def update_table(change):
    selected_dim = dimension_dropdown.value
    selected_year = year_dropdown.value
    df_filtered = df_selected[
        (df_selected["Year"] == selected_year) &
        (df_selected["Governance dimension"] == selected_dim)
    ].sort_values(by="Governance score (0-100)", ascending=False)
    display(df_filtered.head(20))

# Используем interactive_output, чтобы обновлять таблицу автоматически
out = widgets.interactive_output(update_table, {'change': dimension_dropdown})

# Показываем виджеты и вывод
display(widgets.HBox([dimension_dropdown, year_dropdown]), out)

HBox(children=(Dropdown(description='Dimension:', layout=Layout(width='400px'), options=('va', 'pv', 'ge', 'rq…

Output()

In [120]:
import pandas as pd
import matplotlib.pyplot as plt
import ipywidgets as widgets
from IPython.display import display

dimension_dropdown = widgets.Dropdown(
    options=dimensions,
    description='Dimension:',
    value=dimensions[0],
    style={'description_width': 'initial'},
    layout=widgets.Layout(width='400px')
)

year_dropdown = widgets.Dropdown(
    options=sorted(df_selected["Year"].unique(), reverse=True),
    description='Year:',
    value=2024,
    style={'description_width': 'initial'},
    layout=widgets.Layout(width='200px')
)

top_n_slider = widgets.IntSlider(
    value=20,
    min=5,
    max=100,
    step=5,
    description='Top N:',
    style={'description_width': 'initial'},
    layout=widgets.Layout(width='300px')
)

def plot_wgi(dimension, year, top_n):
    df_filtered = df_selected[
        (df_selected["Year"] == year) & 
        (df_selected["Governance dimension"] == dimension)
    ].sort_values(by="Governance score (0-100)", ascending=False).head(top_n)
    
    df_filtered = df_filtered[::-1]  # разворачиваем, чтобы 1 был сверху
    
    plt.figure(figsize=(10, max(5, len(df_filtered)/2)))
    
    bars = plt.barh(range(len(df_filtered)), df_filtered["Governance score (0-100)"], color='green')
    
    # Нумерация стран сверху вниз
    plt.yticks(range(len(df_filtered)), [f"{len(df_filtered)-i}. {c}" for i, c in enumerate(df_filtered["Economy (name)"])])
    
    ax = plt.gca()
    ax.set_ylim(-0.5, len(df_filtered)-0.5)
    
    # Создаём верхнюю ось с такой же шкалой
    ax_top = ax.twiny()
    ax_top.set_xlim(ax.get_xlim())
    ax_top.set_xticks(ax.get_xticks())
    ax_top.set_xticklabels([str(int(x)) for x in ax.get_xticks()])
    
    # Подписи значений справа от столбцов
    for i, v in enumerate(df_filtered["Governance score (0-100)"]):
        ax.text(v + 0.5, i, f"{v:.1f}", va='center', ha='left', fontsize=9, color='black')
    
    # Подписи и сетка
    ax.set_xlabel("Governance score (0-100)")
    plt.title(f"WGI {dimension} - {year}")
    ax.grid(axis='x', linestyle='--', alpha=0.5)
    
    # Убираем лишние отступы
    plt.tight_layout()
    plt.margins(y=0)
    
    plt.show()

out = widgets.interactive_output(plot_wgi, {
    'dimension': dimension_dropdown,
    'year': year_dropdown,
    'top_n': top_n_slider
})

display(widgets.HBox([dimension_dropdown, year_dropdown, top_n_slider]), out)

HBox(children=(Dropdown(description='Dimension:', layout=Layout(width='400px'), options=('va', 'pv', 'ge', 'rq…

Output()

Вариант 2. Americas

In [121]:
df_regions = pd.read_excel("./data/regions.xlsx")

In [122]:
region_code = "AME"  # например, Americas
countries_codes_in_region = df_regions[df_regions["Region"] == region_code]["Code"].tolist()

In [123]:
df_filtered_region = df_selected[df_selected["Economy (code)"].isin(countries_codes_in_region)]
print(df_filtered_region["Economy (name)"].unique())
df_filtered_region.head()

<ArrowStringArray>
[                     'Argentina',                   'Bahamas, The',
                        'Bolivia',                         'Brazil',
                       'Barbados',                         'Canada',
                          'Chile',                       'Colombia',
                     'Costa Rica',                           'Cuba',
                       'Dominica',             'Dominican Republic',
                        'Ecuador',                        'Grenada',
                      'Guatemala',                         'Guyana',
                       'Honduras',                          'Haiti',
                        'Jamaica',                      'St. Lucia',
                         'Mexico',                      'Nicaragua',
                         'Panama',                           'Peru',
                       'Paraguay',                    'El Salvador',
                       'Suriname',            'Trinidad and Tobago',
                        'Uruguay',                  'United States',
 'St. Vincent and the Grenadines',                  'Venezuela, RB']
Length: 32, dtype: str

,Economy (name),Economy (code),Region,Year,Governance dimension,Governance score (0-100),Governance estimate (approx. -2.5 to +2.5),Standard error (gov. score)
5,Argentina,ARG,Latin America & Caribbean,1996,va,64.426408,0.432919,3.378128
18,"Bahamas, The",BHS,Latin America & Caribbean,1996,va,76.082483,1.098886,4.551353
23,Bolivia,BOL,Latin America & Caribbean,1996,va,57.968945,0.063974,3.392431
24,Brazil,BRA,Latin America & Caribbean,1996,va,61.624428,0.272829,3.378128
25,Barbados,BRB,Latin America & Caribbean,1996,va,78.424188,1.232679,4.289510

In [124]:
%pip install plotly
import pandas as pd
import plotly.express as px
import ipywidgets as widgets
from IPython.display import display

# df_filtered_region должен содержать только страны нужного региона
# df_filtered_region = df_selected[df_selected['Economy (name)'].isin(countries_in_region)]

dimensions = df_filtered_region["Governance dimension"].unique()

# Dropdown для метрики
dimension_dropdown = widgets.Dropdown(
    options=dimensions,
    description='Dimension:',
    value=dimensions[0],
    style={'description_width': 'initial'},
    layout=widgets.Layout(width='400px')
)

# Ползунок Top-N стран
top_n_slider = widgets.IntSlider(
    value=10,
    min=1,
    max=min(50, df_filtered_region["Economy (name)"].nunique()),  # максимум 50 или число стран
    step=1,
    description='Top N:',
    style={'description_width': 'initial'},
    layout=widgets.Layout(width='300px')
)

def plot_region_dimension(dimension, top_n):
    # Фильтруем по выбранной метрике
    df_plot = df_filtered_region[df_filtered_region["Governance dimension"] == dimension]
    df_plot = df_plot[["Economy (name)", "Year", "Governance estimate (approx. -2.5 to +2.5)"]]
    
    # Определяем Top-N стран по максимальному estimate
    top_countries = df_plot.groupby("Economy (name)")["Governance estimate (approx. -2.5 to +2.5)"]\
                    .max().sort_values(ascending=False).head(top_n).index
    df_plot = df_plot[df_plot["Economy (name)"].isin(top_countries)]
    
    # Строим интерактивный график
    fig = px.line(
        df_plot, 
        x="Year", 
        y="Governance estimate (approx. -2.5 to +2.5)", 
        color="Economy (name)",
        markers=True,
        hover_data={"Economy (name)": True,
                    "Year": True,
                    "Governance estimate (approx. -2.5 to +2.5)": ':.2f'}
    )
    
    fig.update_layout(
        title=f"WGI Governance Estimate (1996-2024) for region ({dimension})",
        xaxis_title="Year",
        yaxis_title="Governance estimate (-2.5 to +2.5)",
        legend_title="Country",
        template="plotly_white"
    )
    
    fig.show()

# Создаем интерактивный вывод с двумя виджетами
out = widgets.interactive_output(plot_region_dimension, {
    'dimension': dimension_dropdown,
    'top_n': top_n_slider
})

display(widgets.HBox([dimension_dropdown, top_n_slider]), out)

Requirement already satisfied: plotly in /usr/local/lib/python3.11/site-packages (6.6.0)
Requirement already satisfied: narwhals>=1.15.1 in /usr/local/lib/python3.11/site-packages (from plotly) (2.18.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/site-packages (from plotly) (26.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
Note: you may need to restart the kernel to use updated packages.

HBox(children=(Dropdown(description='Dimension:', layout=Layout(width='400px'), options=('va', 'pv', 'ge', 'rq…

Output()

In [125]:
import pandas as pd
import ipywidgets as widgets
from IPython.display import display

# Предположим, что df_filtered_region уже загружен
dimensions = df_filtered_region["Governance dimension"].unique()
years = sorted(df_filtered_region["Year"].unique(), reverse=True)

# Виджет для выбора метрики
dimension_dropdown = widgets.Dropdown(
    options=dimensions,
    description='Dimension:',
    value=dimensions[0],
    style={'description_width': 'initial'},
    layout=widgets.Layout(width='400px')
)

# Виджет для выбора года для анализа max/min
year_dropdown = widgets.Dropdown(
    options=years,
    description='Year:',
    value=2024,
    style={'description_width': 'initial'},
    layout=widgets.Layout(width='200px')
)

# Функция для обновления данных
def update_wgi_stats(dimension, year):
    # Фильтруем по dimension и году
    df_dim = df_filtered_region[df_filtered_region["Governance dimension"] == dimension]
    
    # 1️⃣ Страны с наибольшим и наименьшим WGI за выбранный год
    df_2024 = df_dim[df_dim["Year"] == year][["Economy (name)", "Governance estimate (approx. -2.5 to +2.5)"]]
    max_value = df_2024["Governance estimate (approx. -2.5 to +2.5)"].max()
    min_value = df_2024["Governance estimate (approx. -2.5 to +2.5)"].min()
    max_countries = df_2024[df_2024["Governance estimate (approx. -2.5 to +2.5)"] == max_value]["Economy (name)"].tolist()
    min_countries = df_2024[df_2024["Governance estimate (approx. -2.5 to +2.5)"] == min_value]["Economy (name)"].tolist()
    
    print(f"Страны с наибольшим WGI за {year} (Estimate = {max_value:.2f}): {', '.join(max_countries)}")
    print(f"Страны с наименьшим WGI за {year} (Estimate = {min_value:.2f}): {', '.join(min_countries)}\n")
    
    # 2️⃣ Среднее значение региона по годам
    df_region_estimate = df_dim[["Year", "Governance estimate (approx. -2.5 to +2.5)"]]
    region_mean_per_year = df_region_estimate.groupby("Year").mean().reset_index()
    region_mean_per_year.rename(columns={"Governance estimate (approx. -2.5 to +2.5)":"Regional Mean Estimate"}, inplace=True)
    
    display(region_mean_per_year)

# Создаем интерактивный вывод
out = widgets.interactive_output(update_wgi_stats, {
    'dimension': dimension_dropdown,
    'year': year_dropdown
})

display(widgets.HBox([dimension_dropdown, year_dropdown]), out)

HBox(children=(Dropdown(description='Dimension:', layout=Layout(width='400px'), options=('va', 'pv', 'ge', 'rq…

Output()

In [126]:
import pandas as pd
import plotly.graph_objects as go
import ipywidgets as widgets
from IPython.display import display

dimensions = df_filtered_region["Governance dimension"].unique()

dimension_dropdown = widgets.Dropdown(
    options=dimensions,
    description='Dimension:',
    value=dimensions[0],
    style={'description_width': 'initial'},
    layout=widgets.Layout(width='400px')
)

top_n_slider = widgets.IntSlider(
    value=10,
    min=1,
    max=min(50, df_filtered_region["Economy (name)"].nunique()),
    step=1,
    description='Top N:',
    style={'description_width': 'initial'},
    layout=widgets.Layout(width='300px')
)

def plot_region_dimension(dimension, top_n):
    # Фильтруем по выбранной метрике
    df_plot = df_filtered_region[df_filtered_region["Governance dimension"] == dimension]
    df_plot = df_plot[["Economy (name)", "Year", "Governance estimate (approx. -2.5 to +2.5)"]]
    
    # Top-N стран по максимальному estimate
    top_countries = df_plot.groupby("Economy (name)")["Governance estimate (approx. -2.5 to +2.5)"]\
                    .max().sort_values(ascending=False).head(top_n).index
    df_plot = df_plot[df_plot["Economy (name)"].isin(top_countries)]
    
    # Находим max/min за 2024 год
    df_2024 = df_plot[df_plot["Year"] == 2024]
    max_val = df_2024["Governance estimate (approx. -2.5 to +2.5)"].max()
    min_val = df_2024["Governance estimate (approx. -2.5 to +2.5)"].min()
    max_countries = df_2024[df_2024["Governance estimate (approx. -2.5 to +2.5)"] == max_val]["Economy (name)"].tolist()
    min_countries = df_2024[df_2024["Governance estimate (approx. -2.5 to +2.5)"] == min_val]["Economy (name)"].tolist()
    
    fig = go.Figure()
    
    gray_countries = [c for c in df_plot["Economy (name)"].unique() if c not in max_countries + min_countries]
    # Добавляем все страны серым, без легенды
    for country in gray_countries:
        df_country = df_plot[df_plot["Economy (name)"] == country].sort_values("Year")
        fig.add_trace(go.Scatter(
            x=df_country["Year"],
            y=df_country["Governance estimate (approx. -2.5 to +2.5)"],
            mode='lines+markers',
            line=dict(color='lightgray'),
            marker=dict(color='lightgray'),
            name=country,
            hovertemplate='<b>%{text}</b><br>Year: %{x}<br>Estimate: %{y:.2f}',
            text=[country]*len(df_country),
            showlegend=False
        ))
    
    # Выделяем max страны
    for country in max_countries:
        df_country = df_plot[df_plot["Economy (name)"] == country].sort_values("Year")
        fig.add_trace(go.Scatter(
            x=df_country["Year"],
            y=df_country["Governance estimate (approx. -2.5 to +2.5)"],
            mode='lines+markers',
            line=dict(width=3, color='green'),
            marker=dict(size=8),
            name=f"{country} (max 2024)"
        ))
    
    # Выделяем min страны
    for country in min_countries:
        df_country = df_plot[df_plot["Economy (name)"] == country].sort_values("Year")
        fig.add_trace(go.Scatter(
            x=df_country["Year"],
            y=df_country["Governance estimate (approx. -2.5 to +2.5)"],
            mode='lines+markers',
            line=dict(width=3, color='red'),
            marker=dict(size=8),
            name=f"{country} (min 2024)"
        ))
    
    # Добавляем среднее по региону
    df_mean = df_plot.groupby("Year")["Governance estimate (approx. -2.5 to +2.5)"].mean().reset_index()
    fig.add_trace(go.Scatter(
        x=df_mean["Year"],
        y=df_mean["Governance estimate (approx. -2.5 to +2.5)"],
        mode='lines+markers',
        line=dict(width=3, color='yellow'),
        marker=dict(size=8),
        name="Regional Mean"
    ))
    
    # Добавляем РФ
    df_russia = df_selected[
        (df_selected["Economy (name)"] == "Russian Federation") &
        (df_selected["Governance dimension"] == dimension)
    ][["Year", "Governance estimate (approx. -2.5 to +2.5)"]].sort_values("Year")
    
    if not df_russia.empty:
        fig.add_trace(go.Scatter(
            x=df_russia["Year"],
            y=df_russia["Governance estimate (approx. -2.5 to +2.5)"],
            mode='lines+markers',
            line=dict(width=3, color='blue'),
            marker=dict(size=8),
            name="Russia"
        ))
    
    fig.update_layout(
        title=f"WGI Governance Estimate (1996-2024) for region ({dimension})",
        xaxis_title="Year",
        yaxis_title="Governance estimate (-2.5 to +2.5)",
        template="plotly_white",
        hovermode="closest"
    )
    
    fig.show()

out = widgets.interactive_output(plot_region_dimension, {
    'dimension': dimension_dropdown,
    'top_n': top_n_slider
})

display(widgets.HBox([dimension_dropdown, top_n_slider]), out)

HBox(children=(Dropdown(description='Dimension:', layout=Layout(width='400px'), options=('va', 'pv', 'ge', 'rq…

Output()

In [130]:
import pandas as pd
import ipywidgets as widgets
from IPython.display import display

# df_filtered_region - страны региона Americas
# df_selected - полный датасет с Россией

dimensions = df_selected["Governance dimension"].unique()

dimension_dropdown = widgets.Dropdown(
    options=dimensions,
    description='Dimension:',
    value=dimensions[0],
    style={'description_width': 'initial'},
    layout=widgets.Layout(width='400px')
)

def update_summary_region(dimension):
    # Фильтруем по выбранной метрике для региона
    df_region_score = df_filtered_region[df_filtered_region["Governance dimension"] == dimension][
        ["Economy (name)", "Region", "Year", "Governance score (0-100)"]
    ]
    
    # Добавляем Россию из полного датасета
    df_russia = df_selected[
        (df_selected["Economy (name)"] == "Russian Federation") &
        (df_selected["Governance dimension"] == dimension)
    ][["Economy (name)", "Region", "Year", "Governance score (0-100)"]]
    
    # Объединяем
    df_score = pd.concat([df_region_score, df_russia], ignore_index=True)
    
    # Выбираем 1996 и 2024 годы
    df_1996 = df_score[df_score["Year"] == 1996][["Economy (name)", "Region", "Governance score (0-100)"]].rename(
        columns={"Governance score (0-100)": "WGI 1996"})
    df_2024 = df_score[df_score["Year"] == 2024][["Economy (name)", "Region", "Governance score (0-100)"]].rename(
        columns={"Governance score (0-100)": "WGI 2024"})
    
    # Объединяем по странам
    df_combined = pd.merge(df_1996, df_2024, on=["Economy (name)", "Region"], how="outer")
    df_combined["Изменение (см. пункт 10)"] = df_combined["WGI 2024"] - df_combined["WGI 1996"]
    
    rows = []

    # mean_2024 по региону (без России)
    mean_1996 = df_region_score[df_region_score["Year"] == 1996]["Governance score (0-100)"].mean()
    mean_2024 = df_region_score[df_region_score["Year"] == 2024]["Governance score (0-100)"].mean()
    rows.append({
        "": "mean_2024",
        "Регион": "-",
        "Страна": "-",
        "WGI 1996": mean_1996,
        "WGI 2024": mean_2024,
        "Изменение (см. пункт 10)": mean_2024 - mean_1996
    })

    # max_2024 по региону (без России)
    max_val = df_region_score[df_region_score["Year"] == 2024]["Governance score (0-100)"].max()
    max_rows = df_region_score[
        (df_region_score["Year"] == 2024) &
        (df_region_score["Governance score (0-100)"] == max_val)
    ]
    for _, r in max_rows.iterrows():
        row_1996 = df_combined[df_combined["Economy (name)"] == r["Economy (name)"]]["WGI 1996"].values[0]
        rows.append({
            "": "max_2024",
            "Регион": r["Region"],
            "Страна": r["Economy (name)"],
            "WGI 1996": row_1996,
            "WGI 2024": r["Governance score (0-100)"],
            "Изменение (см. пункт 10)": r["Governance score (0-100)"] - row_1996
        })

    # min_2024 по региону (без России)
    min_val = df_region_score[df_region_score["Year"] == 2024]["Governance score (0-100)"].min()
    min_rows = df_region_score[
        (df_region_score["Year"] == 2024) &
        (df_region_score["Governance score (0-100)"] == min_val)
    ]
    for _, r in min_rows.iterrows():
        row_1996 = df_combined[df_combined["Economy (name)"] == r["Economy (name)"]]["WGI 1996"].values[0]
        rows.append({
            "": "min_2024",
            "Регион": r["Region"],
            "Страна": r["Economy (name)"],
            "WGI 1996": row_1996,
            "WGI 2024": r["Governance score (0-100)"],
            "Изменение (см. пункт 10)": r["Governance score (0-100)"] - row_1996
        })

    # Россия
    if not df_russia.empty:
        r = df_russia[df_russia["Year"] == 2024].iloc[0]
        row_1996 = df_combined[df_combined["Economy (name)"] == r["Economy (name)"]]["WGI 1996"].values[0]
        rows.append({
            "": "Russia",
            "Регион": r["Region"],
            "Страна": "Russia",
            "WGI 1996": row_1996,
            "WGI 2024": r["Governance score (0-100)"],
            "Изменение (см. пункт 10)": r["Governance score (0-100)"] - row_1996
        })
    
    df_summary = pd.DataFrame(rows)
    display(df_summary)

# Интерактивный виджет для региона + Россия
widgets.interactive(update_summary_region, dimension=dimension_dropdown)

interactive(children=(Dropdown(description='Dimension:', layout=Layout(width='400px'), options=('va', 'pv', 'g…

In [ ]:
import pandas as pd
import plotly.express as px
import ipywidgets as widgets
from IPython.display import display

# df_selected должен содержать колонки:
# ["Economy (name)", "Region", "Year", "Governance estimate (approx. -2.5 to +2.5)", "Governance dimension"]

dimensions = df_selected["Governance dimension"].unique()

dimension_dropdown = widgets.Dropdown(
    options=dimensions,
    description='Dimension:',
    value=dimensions[0],
    style={'description_width': 'initial'},
    layout=widgets.Layout(width='400px')
)

def plot_wgi_boxplot(dimension):
    # Фильтруем по выбранной метрике и по 2024 году
    df_plot = df_selected[
        (df_selected["Governance dimension"] == dimension) &
        (df_selected["Year"] == 2024)
    ][["Economy (name)", "Region", "Governance estimate (approx. -2.5 to +2.5)"]].copy()
    
    # Добавим отдельный "All Countries" для объединенного boxplot
    df_plot_all = df_plot.copy()
    df_plot_all["Region"] = "All Countries"
    
    # Объединяем с исходными регионами
    df_box = pd.concat([df_plot, df_plot_all], ignore_index=True)
    
    # Строим boxplot с hover, показывающим страну
    fig = px.box(
        df_box,
        x="Region",
        y="Governance estimate (approx. -2.5 to +2.5)",
        points="all",  # точки для всех стран
        color="Region",
        hover_data={
            "Economy (name)": True,  # выводим название страны
            "Region": True,
            "Governance estimate (approx. -2.5 to +2.5)": ':.2f'
        },
        title=f"WGI Estimate (2024) by Region ({dimension})",
        labels={"Governance estimate (approx. -2.5 to +2.5)": "Governance estimate (-2.5 to +2.5)"},
        template="plotly_white"
    )
    
    fig.update_layout(showlegend=False)
    fig.show()

# Интерактивный вывод
widgets.interactive(plot_wgi_boxplot, dimension=dimension_dropdown)

interactive(children=(Dropdown(description='Dimension:', layout=Layout(width='400px'), options=('va', 'pv', 'g…